Feature 1 : Add Routing to Application
joshsoftware/profile_builder_frontend pull request #1
Opened 2024-05-17 09:26 UTC by Abhishek-Jain-1925

Feature 1 : Add Routing to Application

Work done are as follows - 
1.Added Router file with specified some primary routes.
2.Added dummy templates where required.
3.Installation and Setup of libs.
4.Profile Listing template.

2024-05-17 09:35 UTC, Payal13 requested changes

2024-05-17 09:35 UTC, Payal13 commented on src/components/Login/login.js
fine name should be `.../Login/index.js`

2024-05-17 09:35 UTC, Payal13 commented on src/components/Resume/ListProfiles.js
File name and path - `...components/Profile/List/index.js`

2024-05-17 09:35 UTC, Payal13 commented on src/components/Resume/ListProfiles.js
> +    <div>
use React Fragments instaed of `div` wherever we can

2024-05-17 09:35 UTC, Payal13 commented on src/routes/router.jsx
use .js file

2024-05-17 09:35 UTC, Payal13 commented on src/routes/router.jsx
> +        <Route path="/" element={<Login />} />
path names - 
`/login`
`/profiles`
`/profile-builder`

2024-05-17 10:30 UTC, Abhishek-Jain-1925 commented on src/routes/router.jsx
> +        <Route path="/" element={<Login />} />
Added suggested path names

2024-05-20 09:04 UTC, Payal13 commented on src/components/Login/index.js
> +    <React.Fragment>
You can use like - 
<>
    <h1>Login Page will Appear Here!</h1>
</>

2024-05-20 09:05 UTC, Payal13 commented on src/routes/router.js
> +        <Route path="/dashboard" element={<Dashboard />} />
what is dashboard used for ?

2024-05-20 09:06 UTC, Payal13 approved these changes

2024-05-21 07:43 UTC, Abhishek-Jain-1925 commented on src/routes/router.js
> +        <Route path="/dashboard" element={<Dashboard />} />
HomePage Design for initial Rendering

2024-05-21 07:47 UTC, merged